export const PATH = {
  HOME: '/',
  ERROR_404: '/error404',
  SEGURIDAD_USUARIOS: '/seguridad/usuarios',
  SEGURIDAD_GRUPOS: '/seguridad/grupos',
  EXAMPLE_TEXT_AND_COLORS: '/dashboard/examples/text-and-colors',
  EXAMPLE_BUTTONS: '/dashboard/examples/buttons',
  EXAMPLE_INPUTS_1: '/dashboard/examples/inputs1',
  EXAMPLE_INPUTS_2: '/dashboard/examples/inputs2',
  EXAMPLE_INPUTS_3: '/dashboard/examples/inputs3',
  EXAMPLE_INPUTS_4: '/dashboard/examples/inputs4',
  EXAMPLE_ALERTS: '/dashboard/examples/alerts',
  EXAMPLE_ALERTS_MODAL: '/dashboard/examples/alerts-modal',
  EXAMPLE_LOADERS: '/dashboard/examples/loaders',
  EXAMPLE_MODAL_WINDOWS: '/dashboard/examples/dialogs',
  EXAMPLE_TABLES: '/dashboard/examples/tables',
}
